services:
  routeros:
    image: vaerhme/routeros:latest
    ports:
      - 443:443
      - 8728:8728
      - 8729:8729
    volumes:
      - /dev/net/tun:/dev/net/tun
    entrypoint:
      - /routeros/entrypoint_with_four_interfaces.sh
    cap_add:
      - NET_ADMIN
