name: Go Client Tests
on:
  pull_request:
    branches:
      - 'master'
    paths:
      - '*.go'
      - 'resources/*.yml'
      - '.github/workflows/*.yml'
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        experimental: [false]
        go:
          - 1.22
        os: [ubuntu-latest]
        routeros_version:
          - "7.13"
          - "7.14"
          - "7.15"

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
        id: go  
  
      - name: Get dependencies
        run: | 
          go mod download
      
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58

      - name: Build
        run: go build -v .

      - name: Preparing RouterOS for testing
        run: |
          go run .github/scripts/setup_routeros.go
        env:
          ROS_USERNAME: admin
          ROS_PASSWORD: ''
          ROS_IP_ADDRESS: 127.0.0.1

      - name: Run client tests
        run: go test ./...
        env:
          ROS_HOSTURL: https://127.0.0.1
          ROS_USERNAME: admin
          ROS_PASSWORD: ''
          ROS_INSECURE: true
          ROS_VERSION: ${{ matrix.routeros_version }}

    services:
      routeros:
        image: vaerhme/routeros:v${{ matrix.routeros_version }}
        ports:
          - 443:443
          - 8728:8728
          - 8729:8729
        volumes:
          - /dev/net/tun:/dev/net/tun
        options: >-
          --cap-add=NET_ADMIN
          --entrypoint /routeros/entrypoint_with_four_interfaces.sh
